language: c++

dist: trusty

cache:
    directories:
        - Qt

addons:
    apt:
        packages:
            - git
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - cmake
            - pkg-config
            - libxml2-dev
            - libxslt1-dev
            - libzip-dev
            - libsqlite3-dev
            - libusb-1.0-0-dev
            - libssl-dev
            - libssh2-1-dev
            - libcurl4-openssl-dev
            # Not a subsurface dependency, but a Qt dependency
            - mesa-common-dev

before_install:
    - if [ ! -e Qt/5.9.1 ] ; then
          rm -rf Qt ;
          wget http://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run ;
          chmod +x ./qt-opensource-linux-x64-5.9.1.run ;
          ./qt-opensource-linux-x64-5.9.1.run --platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
      fi
      # TestPreferences uses gui calls, so run a xvfb so it has something to talk to
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"


script:
    - export PATH=$PWD/Qt/5.9.1/gcc_64/bin:$PATH # Make sure correct qmake is found on the $PATH for linuxdeployqt
    - export CMAKE_PREFIX_PATH=$PWD/Qt/5.9.1/gcc_64/lib/cmake ;
      cd .. ;
      bash -e ./subsurface/scripts/build.sh -both -no-bt ;
      bash -e ./subsurface/scripts/build.sh -both
    - env CTEST_OUTPUT_ON_FAILURE=1 make -C subsurface/build check
    - # env CTEST_OUTPUT_ON_FAILURE=1 make -C subsurface/build-mobile check
    - find ./install-root/
    - find . -type f -name subsurface
    - mkdir -p appdir/usr/bin ; cp $(find . -type f -name subsurface) appdir/usr/bin/
    - mkdir -p appdir/ ; cp -r ./install-root ./appdir/usr
    - mkdir -p appdir/usr/share/metainfo ; cp subsurface/appdata/subsurface.appdata.xml appdir/usr/share/metainfo/
    - mkdir -p appdir/usr/share/applications ; cp subsurface/subsurface.desktop appdir/usr/share/applications/
    - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps ; cp subsurface/icons/subsurface-icon.png appdir/usr/share/icons/hicolor/256x256/apps/
    - mv appdir/home/travis/build/probonopd/subsurface/Qt/5.9.1/gcc_64/plugins appdir/usr/
    - rm -rf appdir/usr/home/ appdir/usr/include/
    - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    - chmod a+x linuxdeployqt*.AppImage
    - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
    - ./linuxdeployqt*.AppImage --appimage-extract
    - ./squashfs-root/AppRun ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
    - ./squashfs-root/AppRun ./appdir/usr/share/applications/*.desktop -appimage

after_success:
    - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
    - curl --upload-file ./Subsurface*.AppImage https://transfer.sh/Subsurface-git.$(git rev-parse --short HEAD)-x86_64.AppImage
